# Source: lighthouse/templates/jenkins-controller-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: lighthouse-jenkins-token
  labels:
    app: lighthouse-lighthouse
    chart: "lighthouse-0.0.843"
    release: "lighthouse"
    heritage: "Helm"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: secret-infra
  data:
    - name: token
      key: secret/data/lighthouse/jenkins
      property: token
  template:
    metadata:
      labels:
        app: lighthouse-lighthouse
        chart: "lighthouse-0.0.843"
        release: "lighthouse"
        heritage: "Helm"
    type: Opaque
